#!/bin/bash

touch $HOME/.hamonikr/${0##*/}.log
echo "$(date +%Y-%m-%d_%H:%M) : ${0##*/} $1 running." | tee $HOME/.hamonikr/${0##*/}.log

# update hamonikr default logo setting
if [ -f "/home/$USER/.cinnamon/configs/menu@cinnamon.org/0.json" ] ; then
    echo "update hamonikr default logo setting" | tee -a $HOME/.hamonikr/${0##*/}.log
    sed -i 's/"value": "linuxmint-logo-ring-symbolic"/"value": "hamonikr-logo"/g' /home/$USER/.cinnamon/configs/menu@cinnamon.org/0.json
fi

if [ ! -f "/home/$USER/.hamonikr/default_dconf.done" ] ; then

    # delete cache
    if [ -d "/home/$USER/.cache" ] ; then
        echo "Deleted cache" | tee -a $HOME/.hamonikr/${0##*/}.log
        rm -rf /home/$USER/.cache/*
    fi

    # copy applet to user home
    if [ -d "/home/$USER/.cinnamon/configs" ] ; then
        echo "Copy applets" | tee -a $HOME/.hamonikr/${0##*/}.log
        cp -af /usr/share/cinnamon/applets/expo@cinnamon.org /home/$USER/.cinnamon/configs/
        cp -af /usr/share/cinnamon/applets/scale@cinnamon.org /home/$USER/.cinnamon/configs/        
        cp -af /usr/share/cinnamon/applets/user@cinnamon.org /home/$USER/.cinnamon/configs/                
        cp -af /usr/share/cinnamon/applets/xrandr@cinnamon.org /home/$USER/.cinnamon/configs/
    fi

    # Albert Launcher Settings
    if [ -d "/etc/skel/.config/albert" ] ; then
        echo "copy albert launcher setting" | tee -a $HOME/.hamonikr/${0##*/}.log
        cp -af /etc/skel/.config/albert /home/$USER/.config/
    fi                
    
    # gnome-terminal 설정
    if [ -f "/home/$USER/.hamonikr/hamonikr-terminal.dconf" ] ; then
        echo "update default terminal settings"  | tee -a $HOME/.hamonikr/${0##*/}.log
        dconf load /org/gnome/terminal/legacy/profiles:/:`gsettings list-recursively org.gnome.Terminal.ProfilesList | grep default | cut -d' ' -f3 | tr -d "'"`/ < /home/$USER/.hamonikr/hamonikr-terminal.dconf
    fi

    # nimf 입력기 설정
    if command -v nimf &> /dev/null
    then
        echo "update default nimf settings"  | tee -a $HOME/.hamonikr/${0##*/}.log    
        im-config -n nimf
    fi

    # 단축키
    if command -v shutter &> /dev/null ; then
        if ! command -v fsearch &> /dev/null ; then
            echo "update default keyboard shortcut settings for shutter"  | tee -a $HOME/.hamonikr/${0##*/}.log        
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><Shift>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'shutter -s'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '특정영역 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Primary><Alt>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'shutter -w'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name '선택한 윈도우 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0','custom1']"
        else
            echo "update default keyboard shortcut settings for shutter and fsearch"  | tee -a $HOME/.hamonikr/${0##*/}.log                
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><ALT><Shift>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'shutter -s'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '특정영역 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Primary><Alt>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'shutter -w'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name '선택한 윈도우 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ binding "['<Primary><Shift>f']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ command 'fsearch'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ name '데스크탑 검색'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0','custom1','custom2']"
        fi
    else
        if command -v fsearch &> /dev/null ; then    
            echo "update default keyboard shortcut settings for fsearch"  | tee -a $HOME/.hamonikr/${0##*/}.log                
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><Shift>f']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'fsearch'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '데스크탑 검색'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0']"
        fi
    fi

    # search provider
    echo "update search provider settings"  | tee -a $HOME/.hamonikr/${0##*/}.log    
    cp -a /usr/share/cinnamon/search_providers/google@hamonikr.org $HOME/.local/share/cinnamon/search_providers/google@hamonikr.org
    gsettings set org.cinnamon enabled-search-providers [\"google@hamonikr.org\"]

    echo "created settins-done file"  | tee -a $HOME/.hamonikr/${0##*/}.log        
    touch /home/$USER/.hamonikr/default_dconf.done

    # fix asbru-cm font
    if [ -f "/home/$USER/.config/asbru/asbru.yml" ] ; then
        echo "Update asbru font seting" | tee -a $HOME/.hamonikr/${0##*/}.log
        sed -i 's/Monospace/Droid Sans Mono/g' /home/$USER/.config/asbru/asbru.yml
    fi

    # figlet LOGO
    if [ -f "$HOME/.bashrc" ]; then
        # if "figlet" text in .bashrc
        if [ -z "`cat $HOME/.bashrc | grep figlet`" ]; then
            echo "Update figlet setting" | tee -a $HOME/.hamonikr/${0##*/}.log
            echo 'figlet "$HOSTNAME"' >> $HOME/.bashrc
        fi
    fi

    # Desktop Community Icon
    if [ -f "/usr/share/applications/hamonikrorg.desktop" ]; then
        echo "Update hamonikr community link icon" | tee -a $HOME/.hamonikr/${0##*/}.log
        if [ -d "$HOME/Desktop" ]; then
            cp /usr/share/applications/hamonikrorg.desktop $HOME/Desktop/hamonikrorg.desktop
        else
            cp /usr/share/applications/hamonikrorg.desktop $HOME/바탕화면/hamonikrorg.desktop
        fi
    fi
fi
